server:
  port: 8082
  jpa:
    generate-ddl: true
  undertow: 
    ioThreads: 15
    workerThreads: 150
    accesslog: 
      enabled: true
  compression: 
    enabled: true
    mimeTypes: text/xml, text/css, text/html, application/json
    minResponseSize: 4096

spring: 
  datasource: 
    name: productdb
  application: 
    name: gaurav-bytes-rest-jpa